//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class booking
    {
        public int bk_id { get; set; }
        public Nullable<int> bk_usr_id_fk { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Mobile No is required..!!!")]
        [MinLength(10, ErrorMessage = "Minimum 10 digits")]
        [MaxLength(10, ErrorMessage = "Maximum 10 digits")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        public string bk_mobile { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email ID is required..!!!")]
        [DataType(DataType.EmailAddress)]
        public string bk_mail { get; set; }
        public Nullable<System.DateTime> bk_cal { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Type Your Quries...!!!")]
        public string bk_msg { get; set; }
        public Nullable<int> bk_cat_id_fk { get; set; }
        public Nullable<int> bk_pro_id_fk { get; set; }
    
        public virtual category category { get; set; }
        public virtual person person { get; set; }
        public virtual tbl_usr tbl_usr { get; set; }
    }
}
