//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Table
    {
        public int ID { get; set; }
        public string CrName { get; set; }
        public string CrEmail { get; set; }
        public string CrFile { get; set; }
        public string CrMsg { get; set; }
    }
}
