//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ccon_Table
    {
        public int ID { get; set; }
        public string Cname { get; set; }
        public string Cemail { get; set; }
        public string Cmobile { get; set; }
        public string Cmsg { get; set; }
    }
}
