//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contact_dbEntities : DbContext
    {
        public Contact_dbEntities()
            : base("name=Contact_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<Car_Table> Car_Table { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<Ccon_Table> Ccon_Table { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_usr> tbl_usr { get; set; }
    }
}
