//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_usr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_usr()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int u_id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Name is required...!!!")]
        public string u_name { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required...!!!")]
        public string u_password { get; set; }
        public string u_img { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Mobile No is required..!!!")]
        [MinLength(10, ErrorMessage = "Minimum 10 digits")]
        [MaxLength(10, ErrorMessage = "Maximum 10 digits")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        public string u_contact { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Email ID is required..!!!")]
        [DataType(DataType.EmailAddress)]
        public string u_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
    }
}
